schema_version: 1

context:
  version: "10.2.1"

package:
  name: oxipng-pybind
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/o/oxipng-pybind/oxipng_pybind-${{ version }}.tar.gz
  sha256: ab74cb98ae8897d8f5022fcd7be9a5a66d527abd9e73d753ccce7564489cdb97

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.8,<2.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - oxipng
      pip_check: true

about:
  summary: Focused Python wrapper for oxipng.
  license: Unlicense
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/pdomain/oxipng-pybind

extra:
  recipe-maintainers:
    - thewchan
